services:
  ts-linkwarden:
    image: tailscale/tailscale:latest
    container_name: ts-linkwarden
    hostname: linkwarden
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}?ephemeral=false
      - TS_EXTRA_ARGS=--advertise-tags=tag:container --reset
      - TS_SERVE_CONFIG=/config/linkwarden.json
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - ${PWD}/state:/var/lib/tailscale
      - ${PWD}/config:/config
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped

  postgres:
    env_file: stack.env
    container_name: linkwarden-postgres
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    network_mode: service:ts-linkwarden

  linkwarden:
    env_file: stack.env
    container_name: linkwarden
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@localhost:5432/postgres
    restart: unless-stopped
    image: ghcr.io/linkwarden/linkwarden:latest
    volumes:
      - ./data:/data/data
    depends_on:
      - postgres
      - ts-linkwarden
    network_mode: service:ts-linkwarden

volumes:
  tailscale_state:
    driver: local
